<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Margin Profit' => 'هامش الربح',
    'account_group' => '',
    'asset_account_id' => '',
    'created_by' => '',
    'updated_at' => '',
    'updated_by' => '',
    'Active Rate' => 'السعر الحالي',
    'Add New Category' => 'أضف نوع جديد',
    'Add New Inventory' => 'اضافة مخزن جديد',
    'Add New Item' => 'اضافة صنف جديد',
    'Address' => 'العنوان',
    'Alias' => 'اختصار',
    'Buying Price' => 'سعر الشراء',
    'Category' => 'النوع',
    'Cost of Goods' => 'تكلفة المنتجات',
    'Inventory' => 'المخزن',
    'Invoices' => 'فواتير',
    'Items' => 'اصناف',
    'Name' => 'اسم',
    'Phone No' => 'رقم التلفون',
    'Product' => 'صنف',
    'Quantity' => 'الكمية',
    'Selling Price' => 'سعر البيع',
    'Stock Value' => 'قيمة المخزون',
    'Total' => 'الجملة',
    'Transfere' => 'تحويل',
    'color_class' => 'اللون',
    'created_at' => 'زمن الاضافة',
    'from' => 'من مخزن',
    'item' => 'الصنف',
    'quantity' => 'الكمية',
    'to' => 'الى مخزن',
    'total category items : ' => 'عدد الأصناف في النوع ',
    'total inventory items : ' => 'جملة الأصناف في المخزن',
    'update' => 'تعديل',
];
